### ISSUE TITLE
Write a custom UI bundle for www.sommerfeld.io

### ISSUE THREAD

**Issue by sebastian-sommerfeld-io** [sommerfeld-io/website-ui-bundle#1]
As a DevOps engineer and website owner I want to create a new Antora UI bundle for my website based on the https://gitlab.com/antora/antora-ui-default and following the look and feel from https://docs.github.com.

- [x] Should create a new repo with the name `website-ui` or  `website-ui-bundle` or  `website-theme` or  `website-design`
- [x] Should download and copy the contents from https://gitlab.com/antora/antora-ui-default and build a ui bundle (without any changes for the moment)
- [x] Should add a `CI` workflow which generates a Zip file and stores it somewhere
    - [x] Should validate the Dockerfile with hadolint
    - [x] Should be stored as workflow asset first
    - [x] Should be refactored to store the zip somewhere else
        - :zap: Problem with workflow assets: when a workflow run finishes and an artifact is downloaded [...], a zip is dynamically created with all the file contents that were uploaded. One of the consequences of this limitation is that if a zip is uploaded during a workflow run and then downloaded from the UI, there will be a double zip created. See https://github.com/actions/upload-artifact#limitations
        - :bulb: Maybe use a github release named "CI" or "SNAPSHOT" or "UNSTABLE" or similar and always update this release with unstable builds. Save zip file to this release. :question: Can I update an existing release? Or do I have to delete and create a new release? With the release comes a tag which I would have to update as well. :zap: Don't do this. Only publish releases !!!
        - :question: Is this really what I want? Do I really have to save unstable builds? Or can I just use them locally and store only released builds?
        - [x] Write an ADR about this: https://github.com/sommerfeld-io/website-ui-bundle/blob/main/docs/modules/ADR/pages/2023-06-26-release-artifacts.adoc
- [x] Should add a `Release` workflow which generates a github release, tags the repo and adds a zip file to the release
- [x] Should #8

### Change the look and feel
The look and feel should follow the designs from https://docs.github.com. Maybe take some inspiration from https://gatling.io/docs/gatling. Maybe even think about some design elements from https://www.ubuntu.com or https://sonarcloud.io/summary/new_code?id=sommerfeld-io_website.

:warning: Do not tangle with the CSS too much at the beginning. Only change colors and fonts and maybe font-sizes and line-heights. Otherwise it might be too easy to break visibility on mobile phones etc.

- [x] Should update the header nav and link to my profiles on GitHub (sommerfeld-io) and DockerHub ... Think about preserving the dropdown for something
- [x] Should display links to GitHub and dockerhub in header (and footer) nav as icon instead of text (consider #6)
- [x] Should mirror the header nav in the footer as well
- [x] Should add copyright (year generated dynamically) and legal links to the footer (see https://docs.github.com/en). Should maybe add contact information as well.
- [x] Should add "Contact, Terms, Privacy" page and link from footer
- [x] Should change the default font to Ubuntu from Google Fonts (consider #2!)
- [x] Should change dropdown colors
- [x] Should think about reverting the version in the `antora.yml` at the end of the release pipeline ... Otherwise there might be two antora components with the same version (main branch which uses a version number incorrectly and the version which correctly uses its version number).
- [x] Change Link hover in Toc and left navigation
- [x] Should serve ui-bundle-zip from a local webserver to use in local antora builds (#7)
    - [x] Should update https://github.com/sommerfeld-io/website to use the locally served UI bundle
- [x] Should add some sort of tiles layout for landing pages / index pages about a certain topic (https://docs.github.com/en/get-started or https://ubuntu.com/blog or some other sort of tiles)
- [x] Should update code block styles
- [x] Should style admonition blocks

### Todos following the design changes
- [x] Update README -> Put list with "Github Repository" and "Where to file issues" under "About this project"
- [x] Update PlantUML diagrams to fit the dark design
- [x] Replace dummy text with real content: http://localhost:7888/website/main/contact-terms-privacy.html
- [x] Replace dummy text with real content: http://localhost:7888/website/main/index.html

### Enhancements
- [x] #6
- [x] Should update the build to docker compose :question: This would ensure that the UI bundle, which is served through the webserver, is the latest development and is linted properly. Do the following steps in sequence (have each container depend on the previous): 
    - build helper
    - then run preview (detached)
    - then build image
    - then build and run bundle-server (detached) on port 5555
    - _Don‘t forget to install node-modules_
- [x] Should #13
- [x] Should #15

**Comment by sebastian-sommerfeld-io** [comment]
### Enhancements
- [ ] #6
